channels:
  # - anaconda
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - termcolor
  - easydict
  - ipdb
  - pytorch==1.13.0
  - torchvision==0.14.0
  # - torchaudio==0.13.0
  - cudatoolkit==11.6
  - tqdm
  - scikit-learn
  - imageio
  - matplotlib
  - tensorboard
  - torchmetrics==0.9.3
  - pip
  - pip:
    - prefetch_generator
    - colored-traceback
    - torch-ema
    - gdown==4.6.0
    - clean-fid==0.1.35
    - rich
    - lmdb
    - wandb
    - scikit-image
    - scikit-fmm
    - diffusers
    - scikit-video
